# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeneradorTrajectes
                                 A QGIS plugin
 GeneradorTrajectes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-21
        copyright            : (C) 2018 by Josep Lopez
        email                : jlopez@tecnocampus.cat
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeneradorTrajectes class from file GeneradorTrajectes.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GeneradorTrajectes import GeneradorTrajectes
    return GeneradorTrajectes(iface)
